version: '3.3'

services:
  mysql:
    build: mysql/.
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=forwarding-proxy
      - MYSQL_USER=forwarding-proxy
      - MYSQL_PASSWORD=forwarding-proxy
      - MYSQL_LOWER_CASE_TABLE_NAMES=1
    volumes:
      - ./mount/mysql_data:/var/lib/mysql:rw
    restart: "no"
  forwarding-proxy:
    image: ninetom/forwarding-proxy
    depends_on:
      - mysql
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./mount/proxy_data:/proxy:rw
    environment:
      - SPRING_CONFIG_NAME=application
      - SPRING_CONFIG_LOCATION=file:///proxy/
    command:
      - -jar
      - app.jar
